# -- port number --
server:
  port: 8085

# -- eureka server configuration --
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

# -- api gateway configuration --
spring:
  application:
    name: API-GATEWAY-SERVICE
  output:
    ansi:
      enabled: ALWAYS
  cloud:
    gateway:
      routes:
        - id: USER-PROFILE-SERVICE
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/user/**
        - id: AUTHENTICATION-SERVICE
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/auth/**
        - id: SPORTS-SERVICE
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/sports/**
        - id: WISHLIST-SERVICE
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/wishlist/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

# -- logging --
logging:
  file:
    name: ./logs/apigateway-logs.log
  level:
    root: INFO